---
language: ruby
script: "bundle exec rake spec"
rvm:
  - 1.9.3
notifications:
  hipchat:
    rooms:
      secure: "ShqKM9T+HmhOnUb3l+3Ae1fbVKci2ib8k2feZXFq0UgIyeZROljkgEof8yJ8wg5FYlhhtwJ6RygbUc0XgiHrl8+tI8ujpyu+/LXL+E8QnfQnsBzFP/ZJakfwPnzDsGi3yz46AIvtH347gc2mDk6etyXqhPqCCejX7b9J3nLdtTo="
